<?php

namespace Oratorysignout\Models;

/**
 * LogsStudents
 * 
 * @package OratorysignoutModels
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-09-14, 20:30:14
 */
class LogsStudents extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $student_id;

    /**
     *
     * @var string
     * @Column(type="string", length=14, nullable=false)
     */
    public $timestamp;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=false)
     */
    public $room_from;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=true)
     */
    public $room_to;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSource("logs__students__");
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'logs__students__';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return LogsStudents[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return LogsStudents
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
