<?php

namespace Oratorysignout\Models;

/**
 * SchedulesPeriods
 *
 * @package Oratorysignout\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-04-27, 16:23:50
 */
class SchedulesPeriods extends \Phalcon\Mvc\Model
{

	/**
	 *
	 * @var string
	 * @Column(type="string", length=20, nullable=false)
	 */
	public $schedule_id;

	/**
	 *
	 * @var integer
	 * @Column(type="integer", length=1, nullable=false)
	 */
	public $period;

	/**
	 *
	 * @var integer
	 * @Column(type="integer", length=4, nullable=false)
	 */
	public $start_time;

	/**
	 *
	 * @var integer
	 * @Column(type="integer", length=4, nullable=false)
	 */
	public $end_time;

	/**
	 * Initialize method for model.
	 */
	public function initialize()
	{
		$this->belongsTo('schedule_id', 'Oratorysignout\Models\Schedules', 'id', ['alias' => 'Schedules']);
	}

	/**
	 * Returns table name mapped in the model.
	 *
	 * @return string
	 */
	public function getSource()
	{
		return 'schedules__periods';
	}

	/**
	 * Allows to query a set of records that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return SchedulesPeriods[]
	 */
	public static function find($parameters = null)
	{
		return parent::find($parameters);
	}

	/**
	 * Allows to query the first record that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return SchedulesPeriods
	 */
	public static function findFirst($parameters = null)
	{
		return parent::findFirst($parameters);
	}

	/**
	 * @return array
	 */
	public function jsonSerialize()
	{
		return [
			'period' => (int)$this->period,
			'start_time' => (int)$this->start_time,
			'end_time' => (int)$this->end_time,
		];
	}

}
