<?php

namespace Oratorysignout\Models;

use Phalcon\Db\Column;
use Phalcon\Mvc\Model\MetaData;

/**
 * SchedulesExceptions
 *
 * @package Oratorysignout\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-04-27, 16:24:09
 */
class SchedulesExceptions extends \Phalcon\Mvc\Model
{

	/**
	 *
	 * @var string
	 * @Primary
	 * @Column(type="string", length=8, nullable=false)
	 */
	public $date;

	/**
	 *
	 * @var integer
	 * @Column(type="integer", length=1, nullable=true)
	 */
	public $ignored;

	/**
	 *
	 * @var string
	 * @Column(type="string", length=20, nullable=true)
	 */
	public $schedule_id;

	/**
	 * Initialize method for model.
	 */
	public function initialize()
	{
		$this->belongsTo('schedule_id', 'Oratorysignout\Models\Schedules', 'id', ['alias' => 'Schedule']);
	}

	/**
	 * @return array
	 */
	public function metaData()
	{
		return [
			MetaData::MODELS_ATTRIBUTES => [
				"date",
				"ignored",
				"schedule_id",
			],

			MetaData::MODELS_PRIMARY_KEY => [
			],

			MetaData::MODELS_NON_PRIMARY_KEY => [
				"date",
				"ignored",
				"schedule_id",
			],

			// Every column that doesn't allows null values
			MetaData::MODELS_NOT_NULL => [
				"date",
				"ignored",
				"schedule_id",
			],

			// Every column and their data types
			MetaData::MODELS_DATA_TYPES => [
				"date" => Column::TYPE_BIGINTEGER,
				"ignored" => Column::TYPE_BOOLEAN,
				"schedule_id" => Column::TYPE_BIGINTEGER,
			],

			// The columns that have numeric data types
			MetaData::MODELS_DATA_TYPES_NUMERIC => [
				"date" => true,
				"schedule_id" => true,
			],

			// The identity column, use boolean false if the model doesn't have
			// an identity column
			MetaData::MODELS_IDENTITY_COLUMN => false,

			// How every column must be bound/casted
			MetaData::MODELS_DATA_TYPES_BIND => [
				"date" => Column::BIND_PARAM_INT,
				"ignored" => Column::BIND_PARAM_BOOL,
				"schedule_id" => Column::BIND_PARAM_INT,
			],

			// Fields that must be ignored from INSERT SQL statements
			MetaData::MODELS_AUTOMATIC_DEFAULT_INSERT => [],

			// Fields that must be ignored from UPDATE SQL statements
			MetaData::MODELS_AUTOMATIC_DEFAULT_UPDATE => [],

			// Default values for columns
			MetaData::MODELS_DEFAULT_VALUES => [
				"ignored" => false,
			],

			// Fields that allow empty strings
			MetaData::MODELS_EMPTY_STRING_VALUES => [
			],
		];
	}

	/**
	 * @param mixed $parameters
	 * @return Schedules
	 */
	public function getSchedule($parameters = null)
	{
		return $this->getRelated('Schedule', $parameters);
	}

	/**
	 * Returns table name mapped in the model.
	 *
	 * @return string
	 */
	public function getSource()
	{
		return 'schedules__exceptions';
	}

	/**
	 * Allows to query a set of records that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return SchedulesExceptions[]
	 */
	public static function find($parameters = null)
	{
		return parent::find($parameters);
	}

	/**
	 * Allows to query the first record that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return SchedulesExceptions
	 */
	public static function findFirst($parameters = null)
	{
		return parent::findFirst($parameters);
	}

}
