<?php

namespace Oratorysignout\Models;

/**
 * Schedules
 *
 * @package Oratorysignout\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-04-27, 16:23:05
 */
class Schedules extends \Phalcon\Mvc\Model
{

	/**
	 *
	 * @var string
	 * @Primary
	 * @Column(type="string", length=20, nullable=false)
	 */
	public $id;

	/**
	 *
	 * @var string
	 * @Column(type="string", length=50, nullable=false)
	 */
	public $name;

	/**
	 *
	 * @var integer
	 * @Column(type="integer", length=1, nullable=true)
	 */
	public $default;

	/**
	 * Initialize method for model.
	 */
	public function initialize()
	{
		$this->hasMany('id', 'Oratorysignout\Models\SchedulesExceptions', 'schedule_id', ['alias' => 'SchedulesExceptions']);
		$this->hasMany('id', 'Oratorysignout\Models\SchedulesPeriods', 'schedule_id', ['alias' => 'Periods']);
	}

	/**
	 * @param mixed $parameters
	 * @return SchedulesPeriods[]
	 */
	public function getPeriods($parameters = null)
	{
		return $this->getRelated('Periods', $parameters);
	}

	/**
	 * @return Schedules
	 */
	public static function getDefault()
	{
		return self::findFirst('default = 1');
	}

	/**
	 * Returns table name mapped in the model.
	 *
	 * @return string
	 */
	public function getSource()
	{
		return 'schedules__';
	}

	/**
	 * Allows to query a set of records that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return Schedules[]
	 */
	public static function find($parameters = null)
	{
		return parent::find($parameters);
	}

	/**
	 * Allows to query the first record that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return Schedules
	 */
	public static function findFirst($parameters = null)
	{
		return parent::findFirst($parameters);
	}

	/**
	 * @return array
	 */
	public function jsonSerialize()
	{
		return [
			'id' => (int)$this->id,
			'name' => $this->name,
		];
	}

}
