<?php

namespace Oratorysignout\Models;

/**
 * SchedulesExceptions
 *
 * @package Oratorysignout\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-04-27, 16:24:09
 */
class SchedulesExceptions extends \Phalcon\Mvc\Model
{

	/**
	 *
	 * @var string
	 * @Primary
	 * @Column(type="string", length=8, nullable=false)
	 */
	public $date;

	/**
	 *
	 * @var integer
	 * @Column(type="integer", length=1, nullable=true)
	 */
	public $ignored;

	/**
	 *
	 * @var string
	 * @Column(type="string", length=20, nullable=true)
	 */
	public $schedule_id;

	/**
	 * Initialize method for model.
	 */
	public function initialize()
	{
		$this->belongsTo('schedule_id', 'Oratorysignout\Models\Schedules', 'id', ['alias' => 'Schedule']);
	}

	/**
	 * @param mixed $parameters
	 * @return Schedules
	 */
	public function getSchedule($parameters = null)
	{
		return $this->getRelated('Schedule', $parameters);
	}

	/**
	 * Returns table name mapped in the model.
	 *
	 * @return string
	 */
	public function getSource()
	{
		return 'schedules__exceptions';
	}

	/**
	 * Allows to query a set of records that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return SchedulesExceptions[]
	 */
	public static function find($parameters = null)
	{
		return parent::find($parameters);
	}

	/**
	 * Allows to query the first record that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return SchedulesExceptions
	 */
	public static function findFirst($parameters = null)
	{
		return parent::findFirst($parameters);
	}

}
