<?php

namespace Oratorysignout\Models;

/**
 * SchedulesQuarters
 *
 * @package Oratorysignout\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-04-27, 16:24:17
 */
class SchedulesQuarters extends \Phalcon\Mvc\Model
{

	/**
	 *
	 * @var integer
	 * @Primary
	 * @Column(type="integer", length=1, nullable=false)
	 */
	public $quarter_num;

	/**
	 *
	 * @var integer
	 * @Column(type="integer", length=4, nullable=false)
	 */
	public $start_date;

	/**
	 *
	 * @var integer
	 * @Column(type="integer", length=4, nullable=false)
	 */
	public $end_date;

	/**
	 * Initialize method for model.
	 */
	public function initialize()
	{
		$this->hasMany('quarter_num', 'Oratorysignout\Models\StudentsSchedules', 'quarter', ['alias' => 'StudentsSchedules']);
	}

	/**
	 * Returns table name mapped in the model.
	 *
	 * @return string
	 */
	public function getSource()
	{
		return 'schedules__quarters';
	}

	/**
	 * Allows to query a set of records that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return SchedulesQuarters[]
	 */
	public static function find($parameters = null)
	{
		return parent::find($parameters);
	}

	/**
	 * Allows to query the first record that match the specified conditions
	 *
	 * @param mixed $parameters
	 * @return SchedulesQuarters
	 */
	public static function findFirst($parameters = null)
	{
		return parent::findFirst($parameters);
	}

}
