<?php

namespace Oratorysignout\Models;

/**
 * StudentsSchedules
 * 
 * @package Oratorysignout\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-04-27, 16:24:35
 */
class StudentsSchedules extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $student_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $quarter;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $cycle_day;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $period;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $room;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSource("students__schedules");
        $this->belongsTo('quarter', 'Oratorysignout\Models\SchedulesQuarters', 'quarter_num', ['alias' => 'SchedulesQuarters']);
        $this->belongsTo('student_id', 'Oratorysignout\Models\Students', 'id', ['alias' => 'Students']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'students__schedules';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return StudentsSchedules[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return StudentsSchedules
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
